### ISSUE TITLE
Remove MacOS .DS_Store files

### ISSUE THREAD

**Issue by jcubic** [Technical-writing-mentorship-program/Technicalwritingcourse#64]
They don't belong to the repository and should be put into `.gitignore`.

**Comment by wise4rmgod** [comment]
Thanks, i will remove it now.

**Comment by jcubic** [comment]
You can do this from the terminal:

```
find . -name '.DS_Store' | xargs git rm --cached
```

it will remove the files from git but keep them in your directory.

and then you can add that file to `.gitginore`.

**Comment by wise4rmgod** [comment]
Thanks for the command but it didn't work, so I used this to remove it 
```
git rm --cached '*.DS_Store'

```
